// GENERATED from the iOS export copy table (all four report languages). Do not edit by hand.
package com.hourstracker.app.domain

/** Every user-facing string of an exported report, per language: "en", "he", "ar", "ru". Single-value templates use %s. */
internal object ExportCopyTable {
    val strings: Map<String, Map<String, String>> = mapOf(
        "report.title" to mapOf(
            "en" to "Monthly Hours Report",
            "he" to "דוח שעות חודשי",
            "ar" to "تقرير الساعات الشهري",
            "ru" to "Ежемесячный отчёт о часах",
        ),
        "report.payrollSummary" to mapOf(
            "en" to "Payroll summary",
            "he" to "סיכום שכר",
            "ar" to "ملخص الرواتب",
            "ru" to "Сводка по зарплате",
        ),
        "report.hoursChart" to mapOf(
            "en" to "Hours breakdown",
            "he" to "פילוח שעות",
            "ar" to "توزيع الساعات",
            "ru" to "Распределение часов",
        ),
        "report.payChart" to mapOf(
            "en" to "Pay breakdown",
            "he" to "פילוח שכר",
            "ar" to "توزيع الأجر",
            "ru" to "Распределение оплаты",
        ),
        "report.deductionsChart" to mapOf(
            "en" to "Estimated deductions",
            "he" to "ניכויים משוערים",
            "ar" to "الخصومات التقديرية",
            "ru" to "Примерные удержания",
        ),
        "report.col.incomeTax" to mapOf(
            "en" to "Income tax",
            "he" to "מס הכנסה",
            "ar" to "ضريبة دخل",
            "ru" to "Подоходный налог",
        ),
        "report.col.nationalInsurance" to mapOf(
            "en" to "National insurance",
            "he" to "ביטוח לאומי",
            "ar" to "تأمين وطني",
            "ru" to "Битуах леуми",
        ),
        "report.col.healthTax" to mapOf(
            "en" to "Health tax",
            "he" to "מס בריאות",
            "ar" to "ضريبة صحة",
            "ru" to "Налог на здравоохранение",
        ),
        "report.dailyTable" to mapOf(
            "en" to "Daily details",
            "he" to "פירוט ימים",
            "ar" to "تفاصيل الأيام",
            "ru" to "Данные по дням",
        ),
        "report.allDays" to mapOf(
            "en" to "All days",
            "he" to "כל הימים",
            "ar" to "جميع الأيام",
            "ru" to "Все дни",
        ),
        "report.year" to mapOf(
            "en" to "%s",
            "he" to "%s",
            "ar" to "%s",
            "ru" to "%s",
        ),
        "report.total" to mapOf(
            "en" to "Total",
            "he" to "סה״כ",
            "ar" to "الإجمالي",
            "ru" to "Итого",
        ),
        "report.legend.title" to mapOf(
            "en" to "Column guide",
            "he" to "מדריך עמודות",
            "ar" to "شرح أعمدة الجدول",
            "ru" to "Пояснения к столбцам",
        ),
        "report.worker" to mapOf(
            "en" to "Worker: %s",
            "he" to "עובד: %s",
            "ar" to "العامل: %s",
            "ru" to "Работник: %s",
        ),
        "report.id" to mapOf(
            "en" to "ID number: %s",
            "he" to "תעודת זהות: %s",
            "ar" to "رقم الهوية: %s",
            "ru" to "Номер удостоверения: %s",
        ),
        "report.employee" to mapOf(
            "en" to "Employee number: %s",
            "he" to "מספר עובד: %s",
            "ar" to "رقم الموظف: %s",
            "ru" to "Табельный номер: %s",
        ),
        "report.workplace" to mapOf(
            "en" to "Workplace: %s",
            "he" to "מקום עבודה: %s",
            "ar" to "مكان العمل: %s",
            "ru" to "Место работы: %s",
        ),
        "report.contractor" to mapOf(
            "en" to "Contractor: %s",
            "he" to "קבלן: %s",
            "ar" to "المقاول: %s",
            "ru" to "Подрядчик: %s",
        ),
        "report.period" to mapOf(
            "en" to "Period: %s",
            "he" to "תקופה: %s",
            "ar" to "الفترة: %s",
            "ru" to "Период: %s",
        ),
        "report.creditPoints" to mapOf(
            "en" to "Credit points: %s",
            "he" to "נקודות זיכוי: %s",
            "ar" to "نقاط الائتمان: %s",
            "ru" to "Налоговые пункты: %s",
        ),
        "report.col.day" to mapOf(
            "en" to "Day",
            "he" to "יום",
            "ar" to "اليوم",
            "ru" to "День",
        ),
        "report.col.date" to mapOf(
            "en" to "Date",
            "he" to "תאריך",
            "ar" to "التاريخ",
            "ru" to "Дата",
        ),
        "report.col.in" to mapOf(
            "en" to "In",
            "he" to "כניסה",
            "ar" to "دخول",
            "ru" to "Начало",
        ),
        "report.col.out" to mapOf(
            "en" to "Out",
            "he" to "יציאה",
            "ar" to "خروج",
            "ru" to "Конец",
        ),
        "report.col.break" to mapOf(
            "en" to "Break",
            "he" to "הפסקה",
            "ar" to "استراحة",
            "ru" to "Перерыв",
        ),
        "report.col.totalHours" to mapOf(
            "en" to "Total",
            "he" to "סה״כ",
            "ar" to "المجموع",
            "ru" to "Итого",
        ),
        "report.col.regular" to mapOf(
            "en" to "Regular",
            "he" to "רגיל",
            "ar" to "عادي",
            "ru" to "Обычные",
        ),
        "report.col.ot125" to mapOf(
            "en" to "Overtime 125%",
            "he" to "שעות נוספות 125%",
            "ar" to "إضافي 125%",
            "ru" to "Сверхурочные 125%",
        ),
        "report.col.ot150" to mapOf(
            "en" to "Overtime 150%",
            "he" to "שעות נוספות 150%",
            "ar" to "إضافي 150%",
            "ru" to "Сверхурочные 150%",
        ),
        "report.col.travel" to mapOf(
            "en" to "Travel",
            "he" to "נסיעות",
            "ar" to "مواصلات",
            "ru" to "Проезд",
        ),
        "report.col.dailyWage" to mapOf(
            "en" to "Daily wage",
            "he" to "שכר יומי",
            "ar" to "الأجر اليومي",
            "ru" to "Оплата за день",
        ),
        "report.summary.totalHours" to mapOf(
            "en" to "Total hours",
            "he" to "סה״כ שעות",
            "ar" to "إجمالي الساعات",
            "ru" to "Всего часов",
        ),
        "report.summary.grossPay" to mapOf(
            "en" to "Gross pay",
            "he" to "שכר ברוטו",
            "ar" to "الأجر الإجمالي",
            "ru" to "Брутто",
        ),
        "report.summary.netPay" to mapOf(
            "en" to "Net pay",
            "he" to "שכר נטו",
            "ar" to "الأجر الصافي",
            "ru" to "Нетто",
        ),
        "report.summary.deductions" to mapOf(
            "en" to "Deductions",
            "he" to "ניכויים",
            "ar" to "الخصومات",
            "ru" to "Удержания",
        ),
        "report.legend.day" to mapOf(
            "en" to "Day: weekday name.",
            "he" to "יום: שם יום השבוע.",
            "ar" to "اليوم: اسم يوم الأسبوع.",
            "ru" to "День: день недели.",
        ),
        "report.legend.date" to mapOf(
            "en" to "Date: the work day date.",
            "he" to "תאריך: תאריך יום העבודה.",
            "ar" to "التاريخ: تاريخ يوم العمل.",
            "ru" to "Дата: дата рабочего дня.",
        ),
        "report.legend.in" to mapOf(
            "en" to "In: clock-in time.",
            "he" to "כניסה: שעת התחלת המשמרת.",
            "ar" to "دخول: وقت بداية الوردية.",
            "ru" to "Начало: время начала смены.",
        ),
        "report.legend.out" to mapOf(
            "en" to "Out: clock-out time.",
            "he" to "יציאה: שעת סיום המשמרת.",
            "ar" to "خروج: وقت نهاية الوردية.",
            "ru" to "Конец: время окончания смены.",
        ),
        "report.legend.break" to mapOf(
            "en" to "Break: unpaid break in hours.",
            "he" to "הפסקה: משך הפסקה ללא תשלום בשעות.",
            "ar" to "استراحة: مدة الاستراحة غير المدفوعة بالساعات.",
            "ru" to "Перерыв: неоплачиваемый перерыв в часах.",
        ),
        "report.legend.totalHours" to mapOf(
            "en" to "Total: paid hours after break.",
            "he" to "סה״כ: שעות בתשלום אחרי הפסקה.",
            "ar" to "المجموع: الساعات المدفوعة بعد خصم الاستراحة.",
            "ru" to "Итого: оплачиваемые часы за вычетом перерыва.",
        ),
        "report.legend.rate100" to mapOf(
            "en" to "100%: regular-rate hours.",
            "he" to "100%: שעות בתעריף רגיל.",
            "ar" to "100%: الساعات بالأجر العادي.",
            "ru" to "100%: часы по обычной ставке.",
        ),
        "report.legend.rate125" to mapOf(
            "en" to "125%: first overtime tier.",
            "he" to "125%: שכבת שעות נוספות ראשונה.",
            "ar" to "125%: الشريحة الأولى من الساعات الإضافية.",
            "ru" to "125%: первая ступень сверхурочных.",
        ),
        "report.legend.rate150" to mapOf(
            "en" to "150%: second overtime tier.",
            "he" to "150%: שכבת שעות נוספות שנייה.",
            "ar" to "150%: الشريحة الثانية من الساعات الإضافية.",
            "ru" to "150%: вторая ступень сверхурочных.",
        ),
        "report.legend.travel" to mapOf(
            "en" to "Travel: daily travel allowance.",
            "he" to "נסיעות: תוספת נסיעות יומית.",
            "ar" to "مواصلات: بدل المواصلات اليومي.",
            "ru" to "Проезд: ежедневная компенсация проезда.",
        ),
        "report.legend.dailyWage" to mapOf(
            "en" to "Daily wage: gross pay for that day.",
            "he" to "שכר יומי: השכר ברוטו לאותו יום.",
            "ar" to "الأجر اليومي: الأجر الإجمالي لذلك اليوم.",
            "ru" to "Оплата за день: брутто за этот день.",
        ),
        "fullExport.title" to mapOf(
            "en" to "HoursTracker — Full Data Export",
            "he" to "HoursTracker — ייצוא נתונים מלא",
            "ar" to "HoursTracker — تصدير كامل للبيانات",
            "ru" to "HoursTracker — полный экспорт данных",
        ),
        "fullExport.exportedAt" to mapOf(
            "en" to "Exported",
            "he" to "יוצא בתאריך",
            "ar" to "تاريخ التصدير",
            "ru" to "Дата экспорта",
        ),
        "fullExport.profile" to mapOf(
            "en" to "Profile & settings",
            "he" to "פרופיל והגדרות",
            "ar" to "الملف الشخصي والإعدادات",
            "ru" to "Профиль и настройки",
        ),
        "fullExport.statistics" to mapOf(
            "en" to "Lifetime statistics",
            "he" to "סטטיסטיקה מצטברת",
            "ar" to "إحصاءات إجمالية",
            "ru" to "Общая статистика",
        ),
        "fullExport.sessions" to mapOf(
            "en" to "All work sessions",
            "he" to "כל המשמרות",
            "ar" to "كل الورديات",
            "ru" to "Все смены",
        ),
        "fullExport.activityLog" to mapOf(
            "en" to "Activity log",
            "he" to "יומן פעילות",
            "ar" to "سجل النشاط",
            "ru" to "Журнал действий",
        ),
        "fullExport.totalShifts" to mapOf(
            "en" to "Total shifts",
            "he" to "סה״כ משמרות",
            "ar" to "إجمالي الورديات",
            "ru" to "Всего смен",
        ),
        "fullExport.openShifts" to mapOf(
            "en" to "Open shifts",
            "he" to "משמרות פתוחות",
            "ar" to "ورديات مفتوحة",
            "ru" to "Открытые смены",
        ),
        "fullExport.open" to mapOf(
            "en" to "Open",
            "he" to "פתוחה",
            "ar" to "مفتوحة",
            "ru" to "Открыта",
        ),
        "fullExport.notes" to mapOf(
            "en" to "Notes",
            "he" to "הערות",
            "ar" to "ملاحظات",
            "ru" to "Заметки",
        ),
        "fullExport.payrollStart" to mapOf(
            "en" to "Payroll start day",
            "he" to "יום תחילת חודש שכר",
            "ar" to "يوم بداية شهر الراتب",
            "ru" to "День начала расчётного периода",
        ),
        "fullExport.currency" to mapOf(
            "en" to "Currency",
            "he" to "מטבע",
            "ar" to "العملة",
            "ru" to "Валюта",
        ),
        "fullExport.csv.field" to mapOf(
            "en" to "Field",
            "he" to "שדה",
            "ar" to "الحقل",
            "ru" to "Поле",
        ),
        "fullExport.csv.value" to mapOf(
            "en" to "Value",
            "he" to "ערך",
            "ar" to "القيمة",
            "ru" to "Значение",
        ),
        "fullExport.csv.id" to mapOf(
            "en" to "ID",
            "he" to "מזהה",
            "ar" to "المعرّف",
            "ru" to "ID",
        ),
        "fullExport.csv.isOpen" to mapOf(
            "en" to "Open",
            "he" to "פתוחה",
            "ar" to "مفتوحة",
            "ru" to "Открыта",
        ),
        "fullExport.csv.manual" to mapOf(
            "en" to "Manual",
            "he" to "ידני",
            "ar" to "يدوي",
            "ru" to "Вручную",
        ),
        "fullExport.csv.aiImported" to mapOf(
            "en" to "AI imported",
            "he" to "יובא בבינה מלאכותית",
            "ar" to "مستورد بالذكاء الاصطناعي",
            "ru" to "Импорт с ИИ",
        ),
        "fullExport.csv.dayType" to mapOf(
            "en" to "Day type",
            "he" to "סוג יום",
            "ar" to "نوع اليوم",
            "ru" to "Тип дня",
        ),
        "fullExport.csv.night" to mapOf(
            "en" to "Night shift",
            "he" to "משמרת לילה",
            "ar" to "وردية ليلية",
            "ru" to "Ночная смена",
        ),
        "fullExport.csv.modifiedAt" to mapOf(
            "en" to "Modified",
            "he" to "עודכן",
            "ar" to "آخر تعديل",
            "ru" to "Изменено",
        ),
        "fullExport.csv.effectiveHours" to mapOf(
            "en" to "Effective hours",
            "he" to "שעות אפקטיביות",
            "ar" to "ساعات فعّالة",
            "ru" to "Эффективные часы",
        ),
        "fullExport.csv.basePay" to mapOf(
            "en" to "Base pay",
            "he" to "שכר בסיס",
            "ar" to "أجر أساسي",
            "ru" to "Базовая оплата",
        ),
        "fullExport.csv.ot125Pay" to mapOf(
            "en" to "125% pay",
            "he" to "שכר 125%",
            "ar" to "أجر 125%",
            "ru" to "Оплата 125%",
        ),
        "fullExport.csv.ot150Pay" to mapOf(
            "en" to "150% pay",
            "he" to "שכר 150%",
            "ar" to "أجر 150%",
            "ru" to "Оплата 150%",
        ),
        "fullExport.csv.incomeTax" to mapOf(
            "en" to "Income tax",
            "he" to "מס הכנסה",
            "ar" to "ضريبة دخل",
            "ru" to "Подоходный налог",
        ),
        "fullExport.csv.nationalInsurance" to mapOf(
            "en" to "National insurance",
            "he" to "ביטוח לאומי",
            "ar" to "تأمين وطني",
            "ru" to "Битуах леуми",
        ),
        "fullExport.csv.healthTax" to mapOf(
            "en" to "Health tax",
            "he" to "מס בריאות",
            "ar" to "ضريبة صحة",
            "ru" to "Налог на здравоохранение",
        ),
        "fullExport.csv.timestamp" to mapOf(
            "en" to "Timestamp",
            "he" to "חותמת זמן",
            "ar" to "الطابع الزمني",
            "ru" to "Время",
        ),
        "fullExport.csv.level" to mapOf(
            "en" to "Level",
            "he" to "רמה",
            "ar" to "المستوى",
            "ru" to "Уровень",
        ),
        "fullExport.csv.category" to mapOf(
            "en" to "Category",
            "he" to "קטגוריה",
            "ar" to "الفئة",
            "ru" to "Категория",
        ),
        "fullExport.csv.message" to mapOf(
            "en" to "Message",
            "he" to "הודעה",
            "ar" to "الرسالة",
            "ru" to "Сообщение",
        ),
        "fullExport.csv.details" to mapOf(
            "en" to "Details",
            "he" to "פרטים",
            "ar" to "التفاصيل",
            "ru" to "Подробности",
        ),
    )
}
